// OM Tools — Tool Registry
export const TOOLS = [
  // ── Media Downloaders (YouTube) ──
  {
    id: 'youtube-downloader',
    slug: '/youtube-video-downloader',
    name: 'YouTube Downloader',
    shortName: 'YouTube Video',
    description: 'Download YouTube videos in MP4, WEBM. Supports 4K, 1080p, 720p and more.',
    icon: '▶',
    emoji: '🎬',
    category: 'media',
    platforms: ['youtube'],
    formats: ['MP4', 'WEBM'],
    qualities: ['4K', '1080p', '720p', '480p', '360p', '240p', '144p'],
    isNew: false,
    isPopular: true,
  },
  {
    id: 'youtube-mp3',
    slug: '/youtube-mp3-converter',
    name: 'YouTube to MP3',
    shortName: 'MP3 Converter',
    description: 'Extract high-quality audio from YouTube videos. Download as MP3 or M4A.',
    icon: '🎵',
    emoji: '🎵',
    category: 'media',
    platforms: ['youtube'],
    formats: ['MP3', 'M4A', 'OGG'],
    qualities: ['320kbps', '256kbps', '192kbps', '128kbps'],
    isNew: false,
    isPopular: true,
  },
  {
    id: 'shorts-downloader',
    slug: '/shorts-downloader',
    name: 'Shorts Downloader',
    shortName: 'YT Shorts',
    description: 'Download YouTube Shorts in full quality with one click.',
    icon: '⚡',
    emoji: '⚡',
    category: 'media',
    platforms: ['youtube'],
    formats: ['MP4'],
    qualities: ['1080p', '720p', '480p'],
    isNew: false,
    isPopular: true,
  },
  {
    id: 'youtube-playlist',
    slug: '/youtube-playlist-downloader',
    name: 'Playlist Downloader',
    shortName: 'YT Playlist',
    description: 'Download full YouTube playlists in a single ZIP archive. Supports MP4 videos & MP3 audio.',
    icon: '📂',
    emoji: '📂',
    category: 'media',
    platforms: ['youtube'],
    formats: ['ZIP (MP4)', 'ZIP (MP3)'],
    qualities: ['1080p', '720p', '480p', '360p', '320kbps', '256kbps', '192kbps'],
    isNew: true,
    isPopular: false,
  },

  // ── Social Media Downloaders ──
  {
    id: 'tiktok-downloader',
    slug: '/tiktok-downloader',
    name: 'TikTok Downloader',
    shortName: 'TikTok',
    description: 'Download TikTok videos without watermark in HD quality. Fast, free, no sign-up required.',
    icon: '🎵',
    emoji: '🎵',
    category: 'social',
    platforms: ['tiktok'],
    formats: ['MP4 No Watermark', 'MP3 Audio'],
    qualities: ['HD', 'SD'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'twitter-downloader',
    slug: '/twitter-downloader',
    name: 'Twitter / X Downloader',
    shortName: 'Twitter / X',
    description: 'Download Twitter / X videos and GIFs in HD. Supports tweets, spaces clips, and animated GIFs.',
    icon: '🐦',
    emoji: '🐦',
    category: 'social',
    platforms: ['twitter'],
    formats: ['MP4 HD', 'MP4 SD', 'GIF'],
    qualities: ['1080p', '720p', '480p'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'facebook-downloader',
    slug: '/facebook-downloader',
    name: 'Facebook Video Downloader',
    shortName: 'Facebook',
    description: 'Download Facebook videos from posts, reels, and Watch in HD or SD quality. No account required.',
    icon: '👤',
    emoji: '👤',
    category: 'social',
    platforms: ['facebook'],
    formats: ['MP4 HD', 'MP4 SD'],
    qualities: ['HD', 'SD'],
    isNew: true,
    isPopular: false,
  },
  {
    id: 'reddit-downloader',
    slug: '/reddit-downloader',
    name: 'Reddit Video Downloader',
    shortName: 'Reddit',
    description: 'Download Reddit videos with audio properly merged. Supports all subreddits and formats.',
    icon: '🤖',
    emoji: '🤖',
    category: 'social',
    platforms: ['reddit'],
    formats: ['MP4 HD', 'MP4 SD'],
    qualities: ['HD', 'SD'],
    isNew: true,
    isPopular: false,
  },
  {
    id: 'pinterest-downloader',
    slug: '/pinterest-downloader',
    name: 'Pinterest Video Downloader',
    shortName: 'Pinterest',
    description: 'Download Pinterest video pins and GIFs in full quality. Free, instant, no watermark.',
    icon: '📌',
    emoji: '📌',
    category: 'social',
    platforms: ['pinterest'],
    formats: ['MP4 HD', 'MP4 SD'],
    qualities: ['HD', 'SD'],
    isNew: true,
    isPopular: false,
  },

  // ── Video & Audio Editor (Client-Side / ffmpeg.wasm) ──
  {
    id: 'video-converter',
    slug: '/video-converter',
    name: 'Video Converter',
    shortName: 'Video Converter',
    description: 'Convert any video to MP4, WEBM, MKV, AVI or MOV — entirely in your browser. No upload.',
    icon: '🔄',
    emoji: '🔄',
    category: 'editor',
    platforms: [],
    formats: ['MP4', 'WEBM', 'MKV', 'AVI', 'MOV'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'video-trimmer',
    slug: '/video-trimmer',
    name: 'Video Trimmer',
    shortName: 'Video Trimmer',
    description: 'Cut any video to the exact segment you want. Lossless stream copy. 100% in-browser.',
    icon: '✂️',
    emoji: '✂️',
    category: 'editor',
    platforms: [],
    formats: ['MP4'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'video-compressor',
    slug: '/video-compressor',
    name: 'Video Compressor',
    shortName: 'Video Compressor',
    description: 'Compress videos for WhatsApp & Discord. Choose quality and resolution. 100% private.',
    icon: '🗜️',
    emoji: '🗜️',
    category: 'editor',
    platforms: [],
    formats: ['MP4'],
    qualities: ['1080p', '720p', '480p', '360p'],
    isNew: true,
    isPopular: true,
    badge: '100% Local',
  },
  {
    id: 'video-to-gif',
    slug: '/video-to-gif',
    name: 'Video to GIF',
    shortName: 'GIF Maker',
    description: 'Convert video clips to high-quality animated GIFs with two-pass palette generation.',
    icon: '🎞️',
    emoji: '🎞️',
    category: 'editor',
    platforms: [],
    formats: ['GIF'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'video-muter',
    slug: '/video-muter',
    name: 'Video Muter',
    shortName: 'Video Muter',
    description: 'Remove audio from any video instantly using stream copy. Lightning fast, lossless quality.',
    icon: '🔇',
    emoji: '🔇',
    category: 'editor',
    platforms: [],
    formats: ['MP4'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'audio-extractor',
    slug: '/audio-extractor',
    name: 'Audio Extractor',
    shortName: 'Audio Extractor',
    description: 'Extract audio from any video file. Save as MP3, WAV, AAC or OGG. No upload required.',
    icon: '🎵',
    emoji: '🎵',
    category: 'editor',
    platforms: [],
    formats: ['MP3', 'WAV', 'AAC', 'OGG'],
    qualities: ['320kbps', '256kbps', '192kbps', '128kbps'],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'audio-converter',
    slug: '/audio-converter',
    name: 'Audio Converter',
    shortName: 'Audio Converter',
    description: 'Convert audio between MP3, WAV, FLAC, OGG, AAC and M4A. 100% private, no upload.',
    icon: '🎶',
    emoji: '🎶',
    category: 'editor',
    platforms: [],
    formats: ['MP3', 'WAV', 'FLAC', 'OGG', 'AAC'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'audio-trimmer',
    slug: '/audio-trimmer',
    name: 'Audio Trimmer',
    shortName: 'Audio Trimmer',
    description: 'Cut any audio file to the exact segment you need. Perfect for ringtones and clips.',
    icon: '✂️',
    emoji: '✂️',
    category: 'editor',
    platforms: [],
    formats: ['MP3'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'volume-booster',
    slug: '/volume-booster',
    name: 'Volume Booster',
    shortName: 'Volume Booster',
    description: 'Boost audio volume up to 4×. Perfect for quiet recordings and podcasts. 100% in-browser.',
    icon: '🔊',
    emoji: '🔊',
    category: 'editor',
    platforms: [],
    formats: ['MP3'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },

  // ── Additional Video Editors ──
  {
    id: 'video-merger',
    slug: '/video-merger',
    name: 'Video Merger',
    shortName: 'Video Merger',
    description: 'Join multiple video clips into one seamlessly. Lossless concatenation, 100% in-browser.',
    icon: '🔗',
    emoji: '🔗',
    category: 'editor',
    platforms: [],
    formats: ['MP4'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'video-speed-changer',
    slug: '/video-speed-changer',
    name: 'Video Speed Changer',
    shortName: 'Speed Changer',
    description: 'Speed up or slow down any video from 0.25× to 4×. Audio pitch correction included.',
    icon: '⏩',
    emoji: '⏩',
    category: 'editor',
    platforms: [],
    formats: ['MP4'],
    qualities: [],
    isNew: true,
    isPopular: true,
    badge: '100% Local',
  },
  {
    id: 'video-frame-extractor',
    slug: '/video-frame-extractor',
    name: 'Video Frame Extractor',
    shortName: 'Frame Extractor',
    description: 'Extract any single frame from a video as a high-quality JPG or PNG image.',
    icon: '🖼️',
    emoji: '🖼️',
    category: 'editor',
    platforms: [],
    formats: ['JPG', 'PNG'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'video-cropper',
    slug: '/video-cropper',
    name: 'Video Cropper',
    shortName: 'Video Cropper',
    description: 'Change video aspect ratio: crop 16:9 to 9:16 for Reels, 1:1 for Instagram. 100% in-browser.',
    icon: '✂️',
    emoji: '✂️',
    category: 'editor',
    platforms: [],
    formats: ['MP4'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'video-rotator',
    slug: '/video-rotator',
    name: 'Video Rotator & Flipper',
    shortName: 'Video Rotator',
    description: 'Rotate videos 90°, 180°, 270° or flip horizontally/vertically to fix orientation.',
    icon: '🔃',
    emoji: '🔃',
    category: 'editor',
    platforms: [],
    formats: ['MP4'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },

  // ── Additional Audio Tools ──
  {
    id: 'audio-merger',
    slug: '/audio-merger',
    name: 'Audio Merger',
    shortName: 'Audio Merger',
    description: 'Join multiple audio files into one. Supports MP3, WAV, OGG and more. 100% in-browser.',
    icon: '🔗',
    emoji: '🔗',
    category: 'editor',
    platforms: [],
    formats: ['MP3'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'ringtone-maker',
    slug: '/ringtone-maker',
    name: 'Ringtone Maker',
    shortName: 'Ringtone Maker',
    description: 'Trim audio with fade in/out effects to create perfect ringtones. Export as MP3 or M4R.',
    icon: '🔔',
    emoji: '🔔',
    category: 'editor',
    platforms: [],
    formats: ['MP3', 'M4R'],
    qualities: [],
    isNew: true,
    isPopular: true,
    badge: '100% Local',
  },
  {
    id: 'audio-normalizer',
    slug: '/audio-normalizer',
    name: 'Audio Normalizer',
    shortName: 'Audio Normalizer',
    description: 'Auto-level audio to standard broadcast loudness using ffmpeg loudnorm filter. 100% in-browser.',
    icon: '📊',
    emoji: '📊',
    category: 'editor',
    platforms: [],
    formats: ['MP3', 'WAV'],
    qualities: [],
    isNew: true,
    isPopular: false,
    badge: '100% Local',
  },
  {
    id: 'voice-recorder',
    slug: '/voice-recorder',
    name: 'Voice Recorder',
    shortName: 'Voice Recorder',
    description: 'Record audio from your microphone directly in the browser. Download as MP3 or WAV instantly.',
    icon: '🎙️',
    emoji: '🎙️',
    category: 'editor',
    platforms: [],
    formats: ['WebM', 'WAV'],
    qualities: [],
    isNew: true,
    isPopular: true,
    badge: 'Browser Native',
  },
];


export const CATEGORIES = [
  { id: 'media',  name: 'Media Tools',           description: 'Download & convert media from top platforms' },
  { id: 'social', name: 'Social Downloaders',    description: 'Download from TikTok, Twitter, Facebook, Reddit & more' },
  { id: 'editor', name: 'Video & Audio Editor',  description: 'Process media files locally — 100% private, no upload' },
];


export const SUPPORTED_PLATFORMS = [
  { id: 'youtube',   name: 'YouTube',    color: '#FF0000', emoji: '▶' },
  { id: 'tiktok',   name: 'TikTok',     color: '#69C9D0', emoji: '🎵' },
  { id: 'twitter',  name: 'Twitter/X',  color: '#1DA1F2', emoji: '🐦' },
  { id: 'facebook', name: 'Facebook',   color: '#1877F2', emoji: '👤' },
  { id: 'reddit',   name: 'Reddit',     color: '#FF4500', emoji: '🤖' },
  { id: 'pinterest',name: 'Pinterest',  color: '#E60023', emoji: '📌' },
  { id: 'instagram',name: 'Instagram',  color: '#E1306C', emoji: '📷' },
];

// Detect platform from URL
export function detectPlatform(url) {
  if (!url) return null;
  const u = url.toLowerCase();
  if (u.includes('youtu.be') || u.includes('youtube.com')) {
    if (u.includes('/shorts/')) return { platform: 'youtube', type: 'shorts' };
    if (u.includes('list='))    return { platform: 'youtube', type: 'playlist' };
    return { platform: 'youtube', type: 'video' };
  }
  if (u.includes('instagram.com')) {
    if (u.includes('/reel/'))   return { platform: 'instagram', type: 'reel' };
    if (u.includes('/stories/')) return { platform: 'instagram', type: 'story' };
    return { platform: 'instagram', type: 'post' };
  }
  if (u.includes('tiktok.com'))  return { platform: 'tiktok', type: 'video' };
  if (u.includes('twitter.com') || u.includes('x.com')) return { platform: 'twitter', type: 'tweet' };
  if (u.includes('facebook.com') || u.includes('fb.watch')) return { platform: 'facebook', type: 'video' };
  if (u.includes('reddit.com') || u.includes('redd.it')) return { platform: 'reddit', type: 'video' };
  if (u.includes('pinterest.com') || u.includes('pin.it')) return { platform: 'pinterest', type: 'video' };
  return null;
}

export function isValidUrl(url) {
  try {
    new URL(url);
    return true;
  } catch {
    return false;
  }
}
